"""Initial migration

Revision ID: eea4bad34a32
Revises: 
Create Date: 2026-02-23 14:14:53.095799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eea4bad34a32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('image_prompt_template', sa.Text(), nullable=True),
    sa.Column('example_output', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('max_length_chars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_templates'))
    )
    op.create_table('scrape_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('scrape_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('css_selectors', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_sources'))
    )
    op.create_table('settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('content_slots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=5), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approval_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selected_option_id', sa.Uuid(), nullable=True),
    sa.Column('selected_by', sa.String(length=20), nullable=True),
    sa.Column('selected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_post_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], name=op.f('fk_content_slots_published_post_id_published_posts'), use_alter=True),
    sa.ForeignKeyConstraint(['selected_by_user_id'], ['users.id'], name=op.f('fk_content_slots_selected_by_user_id_users')),
    sa.ForeignKeyConstraint(['selected_option_id'], ['post_options.id'], name=op.f('fk_content_slots_selected_option_id_post_options'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_slots'))
    )
    op.create_index(op.f('ix_content_slots_scheduled_date'), 'content_slots', ['scheduled_date'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('articles_new', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['scrape_sources.id'], name=op.f('fk_scrape_runs_source_id_scrape_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_table('post_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('option_label', sa.String(length=5), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=False),
    sa.Column('body_ru', sa.Text(), nullable=False),
    sa.Column('hashtags', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('image_local_path', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('source_article_ids', sa.Text(), nullable=True),
    sa.Column('ai_quality_score', sa.Float(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['content_slots.id'], name=op.f('fk_post_options_slot_id_content_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_options'))
    )
    op.create_table('published_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('option_id', sa.Uuid(), nullable=False),
    sa.Column('posted_title', sa.String(length=500), nullable=False),
    sa.Column('posted_body', sa.Text(), nullable=False),
    sa.Column('posted_language', sa.String(length=5), nullable=False),
    sa.Column('posted_image_url', sa.String(length=2000), nullable=True),
    sa.Column('telegram_message_id', sa.Integer(), nullable=True),
    sa.Column('telegram_channel_id', sa.String(length=50), nullable=True),
    sa.Column('selected_by', sa.String(length=20), nullable=False),
    sa.Column('selected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['post_options.id'], name=op.f('fk_published_posts_option_id_post_options')),
    sa.ForeignKeyConstraint(['selected_by_user_id'], ['users.id'], name=op.f('fk_published_posts_selected_by_user_id_users')),
    sa.ForeignKeyConstraint(['slot_id'], ['content_slots.id'], name=op.f('fk_published_posts_slot_id_content_slots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_published_posts'))
    )
    op.create_table('scraped_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('scrape_run_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('engagement_potential', sa.Float(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_in_post_id', sa.Uuid(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], name=op.f('fk_scraped_articles_scrape_run_id_scrape_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['scrape_sources.id'], name=op.f('fk_scraped_articles_source_id_scrape_sources')),
    sa.ForeignKeyConstraint(['used_in_post_id'], ['post_options.id'], name=op.f('fk_scraped_articles_used_in_post_id_post_options')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraped_articles'))
    )
    op.create_index(op.f('ix_scraped_articles_url'), 'scraped_articles', ['url'], unique=True)
    op.create_table('channel_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('subscriber_count', sa.Integer(), nullable=False),
    sa.Column('subscriber_growth', sa.Integer(), nullable=False),
    sa.Column('posts_published', sa.Integer(), nullable=False),
    sa.Column('avg_views', sa.Float(), nullable=False),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=False),
    sa.Column('top_post_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['top_post_id'], ['published_posts.id'], name=op.f('fk_channel_snapshots_top_post_id_published_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_snapshots'))
    )
    op.create_index(op.f('ix_channel_snapshots_snapshot_date'), 'channel_snapshots', ['snapshot_date'], unique=True)
    op.create_table('post_analytics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('forwards', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('reactions', sa.Text(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('view_growth_1h', sa.Float(), nullable=True),
    sa.Column('view_growth_24h', sa.Float(), nullable=True),
    sa.Column('hourly_snapshots', sa.Text(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['published_posts.id'], name=op.f('fk_post_analytics_post_id_published_posts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_analytics')),
    sa.UniqueConstraint('post_id', name=op.f('uq_post_analytics_post_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_analytics')
    op.drop_index(op.f('ix_channel_snapshots_snapshot_date'), table_name='channel_snapshots')
    op.drop_table('channel_snapshots')
    op.drop_index(op.f('ix_scraped_articles_url'), table_name='scraped_articles')
    op.drop_table('scraped_articles')
    op.drop_table('published_posts')
    op.drop_table('post_options')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_content_slots_scheduled_date'), table_name='content_slots')
    op.drop_table('content_slots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('scrape_sources')
    op.drop_table('post_templates')
    # ### end Alembic commands ###
